/* Hacettepe il dağılımı: no dependencies, all rendering stays in the browser. */
const provinces = ["Adana","Adıyaman","Afyonkarahisar","Ağrı","Aksaray","Amasya","Ankara","Antalya","Ardahan","Artvin","Aydın","Balıkesir","Bartın","Batman","Bayburt","Bilecik","Bingöl","Bitlis","Bolu","Burdur","Bursa","Çanakkale","Çankırı","Çorum","Denizli","Diyarbakır","Düzce","Edirne","Elazığ","Erzincan","Erzurum","Eskişehir","Gaziantep","Giresun","Gümüşhane","Hakkari","Hatay","Iğdır","Isparta","İstanbul","İzmir","Kahramanmaraş","Karabük","Karaman","Kars","Kastamonu","Kayseri","Kilis","Kırıkkale","Kırklareli","Kırşehir","Kocaeli","Konya","Kütahya","Malatya","Manisa","Mardin","Mersin","Muğla","Muş","Nevşehir","Niğde","Ordu","Osmaniye","Rize","Sakarya","Samsun","Siirt","Sinop","Sivas","Şanlıurfa","Şırnak","Tekirdağ","Tokat","Trabzon","Tunceli","Uşak","Van","Yalova","Yozgat","Zonguldak"];
const demo = provinces.map((il, i) => ({ il, ogrenci_sayisi: Math.round(115 + ((i * 71) % 360) + (["Ankara","İstanbul","İzmir","Bursa","Antalya","Konya"].includes(il) ? 360 : 0)), yil:"Demo", kaynak:"Sentetik demo veri" }));
let records = demo, meta = {yil:"Demo", kaynak:"Sentetik demo veri"};
const $ = id => document.getElementById(id);
const number = n => new Intl.NumberFormat("tr-TR").format(n);
function escapeXml(s){return String(s).replace(/[<>&'"]/g,c=>({"<":"&lt;",">":"&gt;","&":"&amp;","'":"&apos;",'"':"&quot;"}[c]));}
function paint(){
  const sorted = [...records].sort((a,b)=>b.ogrenci_sayisi-a.ogrenci_sayisi), total=records.reduce((s,r)=>s+r.ogrenci_sayisi,0), max=sorted[0]?.ogrenci_sayisi||1, min=Math.min(...records.map(r=>r.ogrenci_sayisi),0);
  $("recordCount").textContent=records.length; $("provinceCount").textContent=records.length; $("totalStudents").textContent=number(total); $("leadingProvince").textContent=sorted[0]?.il||"—"; $("leadingValue").textContent=sorted[0]?number(sorted[0].ogrenci_sayisi)+" öğrenci":"—"; $("yearSource").textContent=`Yıl: ${meta.yil||"Belirtilmedi"} • Kaynak: ${meta.kaynak||"Belirtilmedi"}`; $("previewMeta").textContent=`${meta.yil||"Yıl belirtilmedi"} • ${meta.kaynak||"Kaynak belirtilmedi"}`;
  $("provinceGrid").innerHTML=records.map(r=>{const t=(r.ogrenci_sayisi-min)/(max-min||1), bg=`hsl(335 32% ${94-t*51}%)`;return `<div class="province" style="background:${bg}" title="${escapeXml(r.il)}: ${number(r.ogrenci_sayisi)} öğrenci"><strong>${escapeXml(r.il)}</strong><small>${number(r.ogrenci_sayisi)}</small></div>`}).join("");
  drawChart(sorted.slice(0,10)); drawPreview(sorted.slice(0,5));
}
function drawChart(top){
  const svg=$("rankingChart"), w=760, left=150, chartW=490, max=top[0]?.ogrenci_sayisi||1, row=39; let out=`<title id="chartTitle">İlk 10 ilin öğrenci sayıları</title><desc id="chartDesc">${top.map(x=>`${x.il}: ${number(x.ogrenci_sayisi)} öğrenci`).join(", ")}</desc>`;
  top.forEach((r,i)=>{const y=25+i*row, width=Math.max(4,r.ogrenci_sayisi/max*chartW);out+=`<text x="${left-12}" y="${y+17}" text-anchor="end" class="bar-label">${escapeXml(r.il)}</text><rect x="${left}" y="${y}" width="${width}" height="22" rx="4" fill="${i===0?"#e04b42":"#592d45"}"></rect><text x="${left+width+9}" y="${y+16}" class="bar-value">${number(r.ogrenci_sayisi)}</text>`});svg.innerHTML=out;$("rankingList").innerHTML=top.map(r=>`<li>${escapeXml(r.il)}: ${number(r.ogrenci_sayisi)} öğrenci</li>`).join("");
}
function drawPreview(top){$("previewChart").innerHTML=top.map((r,i)=>`<div class="preview-bar" style="width:${100-i*12}%">${escapeXml(r.il)} · ${number(r.ogrenci_sayisi)}</div>`).join("")}
function parseCsv(text){const lines=text.trim().split(/\r?\n/).filter(Boolean);if(!lines.length)throw Error("CSV boş.");const head=lines.shift().split(",").map(x=>x.trim().toLowerCase());const il=head.indexOf("il"), count=head.indexOf("ogrenci_sayisi");if(il<0||count<0)throw Error("CSV başlıklarında il ve ogrenci_sayisi zorunludur.");return lines.map(line=>{const cells=line.split(",").map(x=>x.trim().replace(/^"|"$/g,""));return {il:cells[il],ogrenci_sayisi:Number(cells[count]),yil:head.includes("yil")?cells[head.indexOf("yil")]:"",kaynak:head.includes("kaynak")?cells[head.indexOf("kaynak")]:""} })}
function validate(rows){if(!Array.isArray(rows)||!rows.length)throw Error("Veri bulunamadı.");const grouped={};rows.forEach(r=>{const il=String(r.il||"").trim(), n=Number(r.ogrenci_sayisi);if(!il||!Number.isFinite(n)||n<0)throw Error("Her satırda geçerli il ve ogrenci_sayisi olmalı.");grouped[il]=(grouped[il]||0)+n});return Object.entries(grouped).map(([il,ogrenci_sayisi])=>({il,ogrenci_sayisi,...rows.find(r=>String(r.il).trim()===il)}))}
async function loadFile(file){try{const text=await file.text(), raw=file.name.toLowerCase().endsWith(".json")?JSON.parse(text):parseCsv(text);records=validate(raw);const first=raw[0]||{};meta={yil:first.yil||"Belirtilmedi",kaynak:first.kaynak||file.name};$("status").className="status";$("status").textContent=`${file.name} yüklendi • ${records.length} il`;paint()}catch(e){$("status").className="status error";$("status").textContent=`Yüklenemedi: ${e.message}`}}
$("fileInput").addEventListener("change",e=>e.target.files[0]&&loadFile(e.target.files[0]));$("demoButton").addEventListener("click",()=>{records=demo;meta={yil:"Demo",kaynak:"Sentetik demo veri"};$("status").className="status";$("status").textContent="Sentetik demo veri gösteriliyor. Gerçek veri değildir.";paint()});
function download(blob,name){const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
$("svgButton").addEventListener("click",()=>download(new Blob([new XMLSerializer().serializeToString($("rankingChart"))],{type:"image/svg+xml"}),"hacettepe-il-siralama.svg"));
$("pngButton").addEventListener("click",()=>{const svg=new XMLSerializer().serializeToString($("rankingChart")),img=new Image(),url=URL.createObjectURL(new Blob([svg],{type:"image/svg+xml"}));img.onload=()=>{const c=document.createElement("canvas");c.width=1520;c.height=880;c.getContext("2d").drawImage(img,0,0,c.width,c.height);c.toBlob(b=>download(b,"hacettepe-il-siralama.png"));URL.revokeObjectURL(url)};img.src=url});
paint();
